"""Generic packaging for World Gal-Game packs.

Wraps PyInstaller to produce a single-folder distributable that bundles
the engine + a chosen pack + the pack's assets. Designed so third-party
game-pack developers can run a single command and ship.

Public API:
    build_pack(
        pack_path: Path,
        *,
        output_dir: Path = Path("dist"),
        target: Literal["current", "windows", "macos", "linux"] = "current",
        app_name: str | None = None,           # auto-derived from pack meta
        icon: Path | None = None,
        onefile: bool = False,
        sign_identity: str | None = None,      # macOS code signing
        clean: bool = True,
    ) -> Path                                  # returns dist/<app_name>/
"""
from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Literal


def _read_pack_title(pack_path: Path) -> str | None:
    """Return the 'title' field from pack_path/content/meta.yaml, or None."""
    meta = pack_path / "content" / "meta.yaml"
    if not meta.exists():
        return None
    # Avoid pulling in PyYAML for a single scalar field.
    text = meta.read_text(encoding="utf-8")
    m = re.search(r"^title:\s+['\"]?(.+?)['\"]?\s*$", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return None


def _safe_name(title: str) -> str:
    """Convert a (possibly non-ASCII) title to a filesystem-safe identifier."""
    # Keep ASCII letters, digits, hyphens, underscores; collapse the rest to _.
    safe = re.sub(r"[^\w\-]", "_", title, flags=re.ASCII)
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe or "MyGame"


def generate_spec(
    pack_path: Path,
    app_name: str,
    output_dir: Path,
    icon: Path | None,
    onefile: bool,
) -> str:
    """Return the text of a PyInstaller .spec file for the given pack.

    This is a pure function — no side effects — so it is straightforward
    to unit-test without invoking PyInstaller.
    """
    # Use the engine's own main.py as the entry point so the bundled binary
    # accepts the same CLI flags as a normal install.
    engine_root = Path(__file__).resolve().parent.parent
    main_py = engine_root / "main.py"

    icon_line = f'    icon={repr(str(icon))},' if icon else "    icon=None,"
    coll_name = f'    name={repr(app_name)},'

    onefile_section = ""
    if onefile:
        onefile_section = f"""
exe_onefile = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name={repr(app_name)},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
{icon_line}
)
"""

    spec = f"""\
# Auto-generated by world_gal_game.build — do not edit by hand.
# Regenerate with: wgg build {pack_path}
from PyInstaller.utils.hooks import collect_submodules
from pathlib import Path

block_cipher = None

# Collect all files from the pack directory so YAML content + assets travel
# with the binary.
pack_path = Path({repr(str(pack_path))})
datas = []
for f in pack_path.rglob("*"):
    if f.is_file():
        rel_parent = f.parent.relative_to(pack_path.parent)
        datas.append((str(f), str(rel_parent)))

hiddenimports = collect_submodules("world_gal_game")
hiddenimports += collect_submodules("pydantic")
try:
    hiddenimports += collect_submodules("anthropic")
except Exception:
    pass

a = Analysis(
    [{repr(str(main_py))}],
    pathex=[{repr(str(engine_root))}],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=["tkinter", "test", "unittest"],
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name={repr(app_name)},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
{icon_line}
    disable_windowed_traceback=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
{coll_name}
)
{onefile_section}"""
    return spec


def build_pack(
    pack_path: Path,
    *,
    output_dir: Path = Path("dist"),
    target: Literal["current", "windows", "macos", "linux"] = "current",
    app_name: str | None = None,
    icon: Path | None = None,
    onefile: bool = False,
    sign_identity: str | None = None,
    clean: bool = True,
) -> Path:
    """Bundle a game pack + engine into a standalone distributable.

    Parameters
    ----------
    pack_path:
        Absolute or relative path to the game pack root (must contain
        ``content/meta.yaml``).
    output_dir:
        Directory where the finished build lands.  Defaults to ``dist/``
        relative to the *current working directory* at call time.
    target:
        ``"current"`` performs a native build on the host platform.
        Any other value prints a cross-build warning and falls back to
        ``"current"`` — PyInstaller cannot cross-compile natively.
    app_name:
        Name for the produced executable / app bundle.  Derived from
        ``content/meta.yaml``'s ``title`` field when omitted.
    icon:
        Path to an icon file (.ico for Windows, .icns for macOS).
    onefile:
        When ``True``, produce a single-file binary instead of a folder.
    sign_identity:
        macOS Developer ID string for ``codesign`` (e.g.
        ``"Developer ID Application: My Company (XXXXXXXX)"``).
        Requires Xcode Command Line Tools on macOS.
    clean:
        Remove ``build/`` and ``dist/`` artefacts from any previous run
        before invoking PyInstaller.

    Returns
    -------
    Path
        Path to the finished output directory (``dist/<app_name>``).

    Raises
    ------
    FileNotFoundError
        If ``pack_path`` does not exist or does not contain
        ``content/meta.yaml``.
    RuntimeError
        If PyInstaller exits with a non-zero status.
    """
    pack_path = Path(pack_path).resolve()

    if not pack_path.exists():
        raise FileNotFoundError(f"pack_path does not exist: {pack_path}")
    meta_yaml = pack_path / "content" / "meta.yaml"
    if not meta_yaml.exists():
        raise FileNotFoundError(
            f"pack_path is missing content/meta.yaml: {pack_path}"
        )

    # Warn about unsupported cross-build targets.
    if target != "current":
        print(
            f"[wgg build] WARNING: target={target!r} — PyInstaller cannot "
            "cross-compile natively. A Docker / Wine environment is required "
            "for cross-platform builds. Falling back to native build.",
            file=sys.stderr,
        )

    # Resolve app_name.
    if app_name is None:
        title = _read_pack_title(pack_path)
        if title:
            app_name = _safe_name(title)
        else:
            app_name = pack_path.name

    output_dir = Path(output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    spec_content = generate_spec(pack_path, app_name, output_dir, icon, onefile)

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".spec",
        prefix=f"wgg_{app_name}_",
        delete=False,
        encoding="utf-8",
    ) as f:
        spec_path = Path(f.name)
        f.write(spec_content)

    try:
        cmd = [
            sys.executable,
            "-m",
            "PyInstaller",
            "--clean",
            "--noconfirm",
            f"--distpath={output_dir}",
            str(spec_path),
        ]
        print(f"[wgg build] {' '.join(cmd)}", flush=True)

        result = subprocess.run(cmd)
        if result.returncode != 0:
            raise RuntimeError(
                f"PyInstaller exited with code {result.returncode}"
            )
    finally:
        spec_path.unlink(missing_ok=True)

    # macOS code signing (best-effort; skip if codesign is not available).
    if sign_identity:
        import platform
        if platform.system() == "Darwin":
            app_bundle = output_dir / app_name / f"{app_name}.app"
            target_for_sign = app_bundle if app_bundle.exists() else output_dir / app_name
            codesign_cmd = [
                "codesign",
                "--deep",
                "--force",
                "--sign",
                sign_identity,
                str(target_for_sign),
            ]
            print(f"[wgg build] {' '.join(codesign_cmd)}", flush=True)
            subprocess.run(codesign_cmd, check=False)
        else:
            print(
                "[wgg build] WARNING: --sign-identity is macOS-only; "
                "skipping code signing on this platform.",
                file=sys.stderr,
            )

    result_path = output_dir / app_name
    print(f"[wgg build] done -> {result_path}", flush=True)
    return result_path


def main(argv: list[str] | None = None) -> int:
    """Argument-parsing entry point shared by build.py and the CLI."""
    import argparse

    p = argparse.ArgumentParser(
        prog="wgg build",
        description=(
            "Package a World Gal-Game pack into a standalone distributable."
        ),
    )
    p.add_argument(
        "pack_path",
        type=Path,
        help="Path to the game pack root (must contain content/meta.yaml).",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=Path("dist"),
        metavar="DIR",
        help="Output directory (default: dist/).",
    )
    p.add_argument(
        "--target",
        choices=["current", "windows", "macos", "linux"],
        default="current",
        help="Build target platform (default: current).",
    )
    p.add_argument(
        "--name",
        default=None,
        metavar="APP_NAME",
        help="Override the app name derived from meta.yaml.",
    )
    p.add_argument(
        "--icon",
        type=Path,
        default=None,
        help="Path to icon file (.ico / .icns).",
    )
    p.add_argument(
        "--onefile",
        action="store_true",
        help="Produce a single-file binary instead of a folder.",
    )
    p.add_argument(
        "--sign-identity",
        default=None,
        metavar="IDENTITY",
        help="macOS Developer ID for code signing.",
    )
    p.add_argument(
        "--no-clean",
        action="store_true",
        help="Do not remove previous build artefacts.",
    )

    args = p.parse_args(argv)

    try:
        out = build_pack(
            args.pack_path,
            output_dir=args.output,
            target=args.target,
            app_name=args.name,
            icon=args.icon,
            onefile=args.onefile,
            sign_identity=args.sign_identity,
            clean=not args.no_clean,
        )
        print(f"Build complete: {out}")
        return 0
    except (FileNotFoundError, RuntimeError) as exc:
        print(f"[wgg build] ERROR: {exc}", file=sys.stderr)
        return 1
