#!/usr/bin/env python3
"""Generate docs/effects-reference.md and docs/conditions-reference.md.

The references are produced from the live capability manifest
(:func:`world_gal_game.dev.capability_manifest.build_manifest`) so they can
never drift from the registry: every effect/condition kind is listed with its
description, its typed arguments (name / type / required / default, from the
JSON-Schema ``args_schema``), the human hint from the freeform ``signature``,
and an auto-generated YAML example.

Usage::

    # Regenerate both reference docs in place (builtins only).
    uv run python tools/gen_references.py

    # Include a pack's plugin-provided kinds too.
    uv run python tools/gen_references.py --pack demo_pack

    # CI / self-check: fail (exit 1) if the on-disk docs are stale.
    uv run python tools/gen_references.py --check

This file owns the two reference docs; do not hand-edit them.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from world_gal_game.dev.capability_manifest import build_manifest  # noqa: E402

DOCS = _REPO_ROOT / "docs"

_AUTOGEN_BANNER = (
    "<!-- AUTO-GENERATED by tools/gen_references.py — do not edit by hand.\n"
    "     Regenerate with: uv run python tools/gen_references.py -->"
)

_EFFECT_INTRO = """\
Effect 是「我要改變遊戲狀態」的宣告。所有 effect 都長這個樣子：

```yaml
{kind: <kind>, target: <id>, value: <number / string / bool>, stat: <optional>}
```

或用簡寫字串 `"kind:target=value"`：

```yaml
"affection:heroine_1=5"       # = {kind: affection, target: heroine_1, value: 5}
"set_flag:met_heroine_1"      # = {kind: set_flag, target: met_heroine_1}
```

每個 kind 的 `args` 欄位附完整型別（取自 `wgg capabilities --schema` 的 JSON
Schema），可用來離線驗證 pack。"""

_CONDITION_INTRO = """\
Condition 是「判斷一件事是否成立」的宣告，用在 `Choice.requires` /
`Choice.forbids` / `Line.requires` / `Scene.requires` 等地方。

```yaml
{kind: <kind>, target: <id>, value: <number / string / list>, stat: <optional>}
```

簡寫字串 `"kind:target=value"`：

```yaml
"flag:met_heroine_1"            # = {kind: flag, target: met_heroine_1}
"affection_gte:heroine_1=25"    # = {kind: affection_gte, target: heroine_1, value: 25}
```"""

_NOTE = """\
> 本檔由 `tools/gen_references.py` 從 capability manifest 自動產生,涵蓋
> **此次執行時 registry 內所有 kind**(含已載入的 plugin)。用
> `uv run python tools/gen_references.py --pack <pack>` 可納入該 pack 的
> plugin kinds。寫 plugin 的方法見 [plugins.md](plugins.md)。"""


def _type_str(prop: dict[str, Any]) -> str:
    """Render a JSON-Schema property fragment into a short type string."""
    if "$ref" in prop:
        return prop["$ref"].split("/")[-1]  # nested model name
    if "anyOf" in prop:
        # Drop the `null` arm: optionality is conveyed by the 必填 column, so
        # `string | null` reads as just `string`. Genuine unions (e.g.
        # array[string] | string) keep both arms.
        parts = [s for p in prop["anyOf"] if (s := _type_str(p)) != "null"]
        return " | ".join(parts) if parts else "any"
    t = prop.get("type")
    if t == "array":
        return f"array[{_type_str(prop.get('items', {}))}]"
    if t is None:
        return "any"
    return str(t)


def _params_table(args_schema: dict[str, Any],
                  signature: dict[str, Any]) -> list[str]:
    """Markdown table rows for an arg model's properties (or [] if none)."""
    props: dict[str, Any] = args_schema.get("properties", {})
    if not props:
        return []
    required = set(args_schema.get("required", []))
    rows = ["| 參數 | 型別 | 必填 | 預設 | 說明 |",
            "|---|---|---|---|---|"]
    for name, prop in props.items():
        typ = _type_str(prop).replace("|", "\\|")  # escape for markdown table
        req = "是" if name in required else "—"
        default = "" if name in required else f"`{prop.get('default')!r}`"
        hint = str(signature.get(name, "")).replace("|", "\\|")
        rows.append(f"| `{name}` | `{typ}` | {req} | {default} | {hint} |")
    return rows


def _example(kind: str, args_schema: dict[str, Any]) -> str:
    """A minimal YAML example using the required params as `<type>` placeholders."""
    props: dict[str, Any] = args_schema.get("properties", {})
    required = list(args_schema.get("required", []))
    parts = [f"kind: {kind}"]
    for name in required:
        parts.append(f"{name}: <{_type_str(props.get(name, {}))}>")
    return "{" + ", ".join(parts) + "}"


def _render(entries: list[dict[str, Any]], *, title: str, intro: str) -> str:
    """Render one reference document from a list of manifest kind entries."""
    out: list[str] = [_AUTOGEN_BANNER, "", f"# {title}", "", intro, "",
                      _NOTE, ""]
    # Group by plugin_id; builtin first, then plugins alphabetically.
    by_plugin: dict[str, list[dict[str, Any]]] = {}
    for e in entries:
        by_plugin.setdefault(e["plugin_id"], []).append(e)
    plugin_order = sorted(by_plugin, key=lambda p: (p != "builtin", p))

    for pid in plugin_order:
        out.append("---")
        out.append("")
        heading = "引擎內建" if pid == "builtin" else f"Plugin: `{pid}`"
        out.append(f"## {heading}")
        out.append("")
        for e in sorted(by_plugin[pid], key=lambda x: x["kind"]):
            out.append(f"### `{e['kind']}`")
            out.append("")
            if e.get("description"):
                out.append(e["description"])
                out.append("")
            schema = e.get("args_schema") or {}
            table = _params_table(schema, e.get("signature") or {})
            if table:
                out.extend(table)
                out.append("")
            out.append("```yaml")
            out.append(f"- {_example(e['kind'], schema)}")
            out.append("```")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_all(*, pack: str | None = None) -> dict[Path, str]:
    """Return {path: content} for both reference docs."""
    manager = None
    if pack:
        from world_gal_game.config import EngineConfig
        from world_gal_game.headless import HeadlessSession
        sess = HeadlessSession.open(EngineConfig(), pack=pack)
        manager = sess.state.meta.get("__plugin_manager__")
    manifest = build_manifest(manager=manager)
    return {
        DOCS / "effects-reference.md": _render(
            manifest["effects"], title="Effects — Full Reference",
            intro=_EFFECT_INTRO),
        DOCS / "conditions-reference.md": _render(
            manifest["conditions"], title="Conditions — Full Reference",
            intro=_CONDITION_INTRO),
    }


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--pack", default=None,
                   help="load a pack first so its plugin kinds are included")
    p.add_argument("--check", action="store_true",
                   help="exit 1 if the on-disk docs differ (CI drift guard)")
    args = p.parse_args(argv)

    rendered = render_all(pack=args.pack)
    if args.check:
        stale = []
        for path, content in rendered.items():
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                stale.append(path.name)
        if stale:
            print(f"[drift] stale reference docs: {', '.join(stale)}\n"
                  f"        run: uv run python tools/gen_references.py",
                  file=sys.stderr)
            return 1
        print("[ok] reference docs are in sync")
        return 0

    for path, content in rendered.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(_REPO_ROOT)} "
              f"({content.count(chr(10)) + 1} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
